#!/usr/bin/env node

/**
 * Generate config.js from .env file
 *
 * This script reads the .env file and generates the js/config.js file
 * with the environment variables properly formatted for the browser.
 *
 * Usage: node scripts/generate-config.js
 */

const fs = require('fs');
const path = require('path');

// Paths
const envPath = path.join(__dirname, '..', '.env');
const configPath = path.join(__dirname, '..', 'js', 'config.js');

// Check if .env exists
if (!fs.existsSync(envPath)) {
    console.error('L Error: .env file not found!');
    console.log('=Ý Please copy .env.example to .env and fill in your credentials');
    process.exit(1);
}

// Read and parse .env file
function parseEnvFile(filePath) {
    const content = fs.readFileSync(filePath, 'utf8');
    const env = {};

    content.split('\n').forEach(line => {
        // Skip comments and empty lines
        if (line.trim().startsWith('#') || !line.trim()) {
            return;
        }

        // Parse KEY=VALUE
        const match = line.match(/^([^=]+)=(.*)$/);
        if (match) {
            const key = match[1].trim();
            const value = match[2].trim();
            env[key] = value;
        }
    });

    return env;
}

// Generate config.js content
function generateConfig(env) {
    return `// Configuration for Main App
// IMPORTANT: This file is auto-generated from .env file
// DO NOT edit this file directly - edit .env instead and run:
// node scripts/generate-config.js
//
// Generated on: ${new Date().toISOString()}

const config = {
    firebase: {
        apiKey: "${env.VITE_FIREBASE_API_KEY || ''}",
        authDomain: "${env.VITE_FIREBASE_AUTH_DOMAIN || ''}",
        projectId: "${env.VITE_FIREBASE_PROJECT_ID || ''}",
        storageBucket: "${env.VITE_FIREBASE_STORAGE_BUCKET || ''}",
        messagingSenderId: "${env.VITE_FIREBASE_MESSAGING_SENDER_ID || ''}",
        appId: "${env.VITE_FIREBASE_APP_ID || ''}",
        measurementId: "${env.VITE_FIREBASE_MEASUREMENT_ID || ''}"
    },
    ai: {
        openaiApiKey: "${env.VITE_OPENAI_API_KEY || ''}",
        anthropicApiKey: "${env.VITE_ANTHROPIC_API_KEY || ''}"
    },
    app: {
        name: "${env.VITE_APP_NAME || 'Sua Pa AI'}",
        url: "${env.VITE_APP_URL || 'http://localhost:3000'}",
        apiBaseUrl: "${env.VITE_API_BASE_URL || 'http://localhost:3000'}"
    }
};

export default config;
`;
}

// Main execution
try {
    console.log('= Reading .env file...');
    const env = parseEnvFile(envPath);

    console.log(' Parsed environment variables');
    console.log(`   - Firebase Project: ${env.VITE_FIREBASE_PROJECT_ID || 'Not set'}`);
    console.log(`   - OpenAI API Key: ${env.VITE_OPENAI_API_KEY ? ' Set' : ' Not set'}`);
    console.log(`   - App Name: ${env.VITE_APP_NAME || 'Sua Pa AI'}`);

    console.log('\n=Ý Generating config.js...');
    const configContent = generateConfig(env);

    // Write config.js
    fs.writeFileSync(configPath, configContent, 'utf8');

    console.log(' Successfully generated js/config.js');
    console.log('\n   SECURITY REMINDER:');
    console.log('   - Make sure .env is in .gitignore');
    console.log('   - Never commit .env to version control');
    console.log('   - Keep your API keys secure\n');

} catch (error) {
    console.error('L Error generating config:', error.message);
    process.exit(1);
}
